name: Update Mojangles Font from FontStruct

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  
jobs:
  update-font:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download TTF from FontStruct
        run: |
          curl -L -o fonts/minecraft_font.ttf "https://fontstruct.com/fontstructions/DEINE_FONT_ID/download/DEINE_FONT_NAME.ttf"

      - name: Install FontForge
        run: sudo apt-get update && sudo apt-get install -y fontforge

      - name: Generate woff and woff2
        run: |
          fontforge -script generate_webfonts.pe fonts/minecraft_font.ttf

      - name: Commit and push updated fonts
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add fonts/minecraft_font.ttf fonts/minecraft_font.woff fonts/minecraft_font.woff2
          git commit -m "Update fonts from FontStruct"
          git push
        continue-on-error: true
