name: Generiere Wiki-Index

on:
  push:
    paths:
      - "wiki/**"
      - "generate-wiki-index.js"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repository klonen
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Node.js installieren
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Abhängigkeiten installieren (falls nötig)
        run: npm install

      - name: Wiki-Index generieren
        run: node generate-wiki-index.js

      - name: Änderungen committen
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add wiki-index.js
          git commit -m "Auto: Wiki-Index aktualisiert" || echo "Keine Änderungen"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
