name: Replace Mojangles with CSS variable

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  replace-font:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Branch
        run: |
          git checkout -b replace-mojangles-varfont-main

      - name: Replace Mojangles in /docs
        run: |
          find ./docs -type f \( -name '*.css' -o -name '*.html' -o -name '*.js' \) -print0 | while IFS= read -r -d '' file; do
            perl -pi -e 's/(font[- ]*family[^;:\n]*?)["'\''`]Mojangles["'\''`]?(?=[,;])/sprintf("%svar(--font-main)", $1)/gie' "$file"
          done

      - name: Commit changes
        run: |
          if git diff --quiet; then
            echo "No changes made."
            exit 0
          fi
          git add .
          git commit -m "Replace Mojangles with CSS var(--font-main)"

      - name: Push branch
        run: git push --set-upstream origin replace-mojangles-varfont-main

      - name: Create Pull Request
        run: |
          gh pr create \
            --title "Replace Mojangles with CSS var" \
            --body "Automatischer PR: Ersetze alle Mojangles mit var(--font-main) in CSS, HTML und JS unter /docs." \
            --base main \
            --head replace-mojangles-varfont-main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
