name: Replace Mojangles with CSS var

on:
  workflow_dispatch:

jobs:
  font-replace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Replace Mojangles in all relevant files
        run: |
          find . -type f \( -name '*.css' -o -name '*.html' -o -name '*.js' \) -print0 | while IFS= read -r -d '' file; do
            perl -pi -e 's/(?<=font[- ]*family[^;:\n]*)["'\''`]Mojangles["'\''`]?/var(--font-main)/g' "$file"
          done
