name: Twitch API Check

on:
  push:
    branches:
      - main

jobs:
  check-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y curl

    - name: Fetch Twitch API Data
      env:
        TWITCH_ACCESS_TOKEN: ${{ secrets.Twitch_API_Access_Token }}
        TWITCH_CLIENT_ID: ${{ secrets.Twitch_API_Client_ID }}
      run: |
        curl -H "Client-ID: $TWITCH_CLIENT_ID" -H "Authorization: Bearer $TWITCH_ACCESS_TOKEN" \
        -X GET "https://api.twitch.tv/helix/streams?user_login=redminer9630" \
        -o twitch_data.json
